name: update-content

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Remove existing contents
        run: |
          rm -rf !VERSION.txt

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: christo070/portfolio-website
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: temp-source-repo

      - name: Copy new contents
        run: |
          cp -r temp-source-repo/dist/* .
          rm -rf temp-source-repo

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            message: 'Update for website'
